### Create a new WebHook in Azure DevOps
# Variables
# <org_name>: Your Azure DevOps organization name
# <webhook_id>: The identifier (GUID) shown in the WebHook URL
# <api-version>: The API version to use (e.g., 6.0-preview)
@org_name = "returngisorg"
@webhook_id = "GHCopilotWH"
@api_version = "7.1-preview.1"


###

POST https://dev.azure.com/returngisorg/_apis/public/distributedtask/webhooks/GHCopilotWH?api-version=7.1-preview.1
Content-Type: application/json; charset=utf-8
# Authorization: Basic {{base64Credentials}}    # Uncomment and set if your webhook uses basic auth
# X-Webhook-Secret: {{yourSecret}}               # Uncomment and set if your webhook expects a custom secret header

{
    "subscriptionId": "9cbf7dd2-673b-4569-b478-1bcf1564a143",
    "notificationId": 1,
    "id": "13838487-defd-4321-bb97-2953307147eb",
    "eventType": "workitem.created",
    "publisherId": "tfs",
    "message": {
        "text": "Task #369 (Second time) created by Daenerys Targaryen 🔥\r\n(https://dev.azure.com/returngisorg/web/wi.aspx?pcguid=969756cc-843a-4763-9ce5-2d20dc9703ab&id=369)",
        "html": "<a href=\"https://dev.azure.com/returngisorg/web/wi.aspx?pcguid=969756cc-843a-4763-9ce5-2d20dc9703ab&amp;id=369\">Task #369</a> (Second time) created by Daenerys Targaryen &#128293;",
        "markdown": "[Task #369](https://dev.azure.com/returngisorg/web/wi.aspx?pcguid=969756cc-843a-4763-9ce5-2d20dc9703ab&id=369) (Second time) created by Daenerys Targaryen 🔥"
    },
    "detailedMessage": {
        "text": "Task #369 (Second time) created by Daenerys Targaryen 🔥\r\n(https://dev.azure.com/returngisorg/web/wi.aspx?pcguid=969756cc-843a-4763-9ce5-2d20dc9703ab&id=369)\r\n\r\n- Area: GitHub Copilot CLI\r\n- Iteration: GitHub Copilot CLI\r\n- State: To Do\r\n",
        "html": "<a href=\"https://dev.azure.com/returngisorg/web/wi.aspx?pcguid=969756cc-843a-4763-9ce5-2d20dc9703ab&amp;id=369\">Task #369</a> (Second time) created by Daenerys Targaryen &#128293;<ul>\r\n<li>Area: GitHub Copilot CLI</li>\r\n<li>Iteration: GitHub Copilot CLI</li>\r\n<li>State: To Do</li></ul>",
        "markdown": "[Task #369](https://dev.azure.com/returngisorg/web/wi.aspx?pcguid=969756cc-843a-4763-9ce5-2d20dc9703ab&id=369) (Second time) created by Daenerys Targaryen 🔥\r\n\r\n* Area: GitHub Copilot CLI\r\n* Iteration: GitHub Copilot CLI\r\n* State: To Do\r\n"
    },
    "resource": {
        "id": 369,
        "rev": 1,
        "fields": {
            "System.AreaPath": "GitHub Copilot CLI",
            "System.TeamProject": "GitHub Copilot CLI",
            "System.IterationPath": "GitHub Copilot CLI",
            "System.WorkItemType": "Task",
            "System.State": "To Do",
            "System.Reason": "Added to backlog",
            "System.CreatedDate": "2025-09-26T07:30:31.653Z",
            "System.CreatedBy": "Daenerys Targaryen 🔥 <daenerys@thegameofthrones.onmicrosoft.com>",
            "System.ChangedDate": "2025-09-26T07:30:31.653Z",
            "System.ChangedBy": "Daenerys Targaryen 🔥 <daenerys@thegameofthrones.onmicrosoft.com>",
            "System.CommentCount": 0,
            "System.Title": "Second time",
            "Microsoft.VSTS.Common.StateChangeDate": "2025-09-26T07:30:31.653Z",
            "Microsoft.VSTS.Common.Priority": 2,
            "System.Description": "<div>Here we go&nbsp;<span>&#128521;</span> </div>"
        },
        "multilineFieldsFormat": {
            "System.Description": "html"
        },
        "_links": {
            "self": {
                "href": "https://dev.azure.com/returngisorg/2dfba5ba-a6f1-47ff-be15-640d542a8310/_apis/wit/workItems/369"
            },
            "workItemUpdates": {
                "href": "https://dev.azure.com/returngisorg/2dfba5ba-a6f1-47ff-be15-640d542a8310/_apis/wit/workItems/369/updates"
            },
            "workItemRevisions": {
                "href": "https://dev.azure.com/returngisorg/2dfba5ba-a6f1-47ff-be15-640d542a8310/_apis/wit/workItems/369/revisions"
            },
            "workItemComments": {
                "href": "https://dev.azure.com/returngisorg/2dfba5ba-a6f1-47ff-be15-640d542a8310/_apis/wit/workItems/369/comments"
            },
            "html": {
                "href": "https://dev.azure.com/returngisorg/2dfba5ba-a6f1-47ff-be15-640d542a8310/_workitems/edit/369"
            },
            "workItemType": {
                "href": "https://dev.azure.com/returngisorg/2dfba5ba-a6f1-47ff-be15-640d542a8310/_apis/wit/workItemTypes/Task"
            },
            "fields": {
                "href": "https://dev.azure.com/returngisorg/2dfba5ba-a6f1-47ff-be15-640d542a8310/_apis/wit/fields"
            }
        },
        "url": "https://dev.azure.com/returngisorg/2dfba5ba-a6f1-47ff-be15-640d542a8310/_apis/wit/workItems/369"
    },
    "resourceVersion": "1.0",
    "resourceContainers": {
        "collection": {
            "id": "969756cc-843a-4763-9ce5-2d20dc9703ab",
            "baseUrl": "https://dev.azure.com/returngisorg/"
        },
        "account": {
            "id": "1d84d65d-2e28-4aa7-8d96-abbbc4c77bfa",
            "baseUrl": "https://dev.azure.com/returngisorg/"
        },
        "project": {
            "id": "2dfba5ba-a6f1-47ff-be15-640d542a8310",
            "baseUrl": "https://dev.azure.com/returngisorg/"
        }
    },
    "createdDate": "2025-09-26T07:30:38.6347213Z"
}